name: Bundle for Windows

on:
  push:
    branches: ["master"]

env:
  PIP_PROGRESS_BAR: "off"

jobs:
  build-win:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
         python-version: '3.12'
         # cache: 'poetry'

    - name: 'Resolve Project Dependencies'
      shell: pwsh # For Linux, use bash
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry self add poetry-pyinstaller-plugin
        poetry install

    - name: 'Build'
      shell: pwsh
      run: poetry build

    - name: 'Store Windows Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: media-renamer-win64
        path: dist\pyinstaller\win_amd64\media_renamer
